### ISSUE TITLE
ReadMe error

### ISSUE THREAD

**Issue by nikAleksandr** [times/doctop#9]
"preserveFormatting (default: true)

This will .... Defaults to false."

Does this default to true or false?  I suspect false, but am not familiar enough with the script yet to know.

**Comment by aendrew** [comment]
Ahaha, wow; that's some high quality documentation there!

Pretty sure it defaults to true. Will take a look and update the documentation accordingly.

**Comment by MattieTK** [comment]
This is correct, fixed the docs and closed the issue (3 months later @aendrew, so lazy).

**Comment by aendrew** [comment]
Thanks @MattieTK! :+1: :shipit: 

--Ændrew, Lazy-Ass Developer
